---
- name: Disable unused services
  hosts: mikrotik-devices
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Disable unused services
      routeros_command:
        commands:
          - /log warning "Start Services configured"
          - /ip service set telnet disabled=yes
          - /ip service set ftp disabled=yes
          - /ip service set api disabled=yes
          - /ip service set api-ssl disabled=yes
          - /ip service set www disabled=yes
          - /ip service set www-ssl disabled=yes
          - /ip service print
      register: ip_service_set_result

    - name: Debug registered var
      debug: var=ip_service_set_result.stdout_lines[7]

    - name: By default, disable the helper'y
      routeros_command:
        commands:
          - /log warning "Start Service ports configured"
          - /ip firewall service-port set ftp disabled=yes
          - /ip firewall service-port set tftp disabled=yes
          - /ip firewall service-port set irc disabled=yes
          - /ip firewall service-port set h323 disabled=yes
          - /ip firewall service-port set sip disabled=yes
          - /ip firewall service-port set pptp disabled=yes
          - /ip firewall service-port set dccp disabled=yes
          - /ip firewall service-port set sctp disabled=yes
          - /ip firewall service-port set udplite disabled=yes
          - /ip firewall service-port print
      register: ip_firewall_service_port_set_result

    - name: Debug registered var
      debug: var=ip_firewall_service_port_set_result.stdout_lines[10]

    - name: Start NTP configured
      routeros_command:
        commands:
          - /log warning "Start NTP configured"
          - /system ntp client set enabled=yes server-dns-names="time1.google.com, time2.google.com, 1.pool.ntp.org, 2.pool.ntp.org"
          - /system ntp client print
          - /system clock set time-zone-name="Europe/Kiev"
      register: system_ntp_client_set_result

    - name: Debug registered var
      debug: var=system_ntp_client_set_result.stdout_lines[2]

    - name: Configuring Users
      routeros_command:
        commands:
          - /log warning "Start Users settings configured";
          - /user add name=AdminUser password=AdminPass group=full;
          - /user remove admin;
      register: user_add_result

    - name: Debug registered var
      debug: var=user_add_result.stdout_lines
