---
- name: Run cfg commands on router
  hosts: mikrotik-devices
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Disable services
      routeros_command:
        commands:
          - /beep
      when: routeros_disable_beep

      register: ip_service_set_result

    - name: Debug registered var
      debug: var=ip_service_set_result.stdout_lines[7]
