---
# tasks file for service
- name: COPY FILE FROM THE NETWORK DEVICE TO ANSIBLE CONTROLLER
  net_put:
    src:  "{{ role_path }}/files/running_cfg_service.rsc"
    protocol: sftp
    dest : running_cfg_service.rsc

- name: File demonstate after
  routeros_command:
    commands: /file print
  register: file_after

- name: debug print after
  debug: var=file_after.stdout_lines

- name: File import
  routeros_command:
    commands: /import file-name=running_cfg_service.rsc
  register: file_import

- name: debug print after
  debug: var=file_import.stdout_lines
