---
# tasks file for security

- name: Disable services
  routeros_command:
    commands:
      - /log warning "Disable services"
      - /ip service disable api,api-ssl,ftp,telnet,www,www-ssl
      - /ip service print
  register: ip_service_set_result

- name: Debug registered var
  debug: var=ip_service_set_result.stdout_lines[2]

- name: Disable services ports
  routeros_command:
    commands:
      - /log warning "Disable services ports"
      - /ip firewall service-port disable dccp,ftp,h323,irc,pptp,sctp,sip,tftp,udplite
      - /ip firewall service-port print
  register: ip_firewall_service_port_set_result

- name: Debug registered var
  debug: var=ip_firewall_service_port_set_result.stdout_lines[2]

- name: Disable MAC-Telnet
  routeros_command:
    commands:
      - /log warning "Disable MAC-Telnet"
      - /tool mac-server set allowed-interface-list=none
      - /tool mac-server print

  register: tool_mac_server_set_result

- name: Debug registered var
  debug: var=tool_mac_server_set_result.stdout_lines[2]
